environment:
  nodejs_version: "8"
   
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - ps: Install-Product node $env:nodejs_version
  - npm install -g gulp
  - "cd webapp\\frontend && npm install && gulp"
  - choco install firefox
  - choco install selenium-gecko-driver

build: off

test_script:
  - "%PYTHON%\\python.exe -m tests.test -v"

after_test:
  - "%PYTHON%\\Scripts\\pyinstaller.exe --clean .\\scoop-viewer.spec"

artifacts:
  - path: dist
    name: scoop-viewer